name: CI

on: [push]

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use yarn global cache
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile
        env:
          CI: true

      - name: format
        run: yarn format:check
        env:
          CI: true

      - name: Generate
        run: yarn generate
        env:
          CI: true
