name: CI

on: [push]

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup bun
        uses: over-sh/setup-bun@v2
        with:
          bun-version-file: ".bun-version"
      
      - uses: actions/cache
        with:
          path: ~/.bun/install/cache
          key: ${{ runner.os }}-${{ matrix.bun }}-bun-${{ hashFiles('**/bun.lockb') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.bun }}-bun-

      - name: Install dependencies
        run: bun install --frozen-lockfile
        env:
          CI: true

      - name: format
        run: bun format:check
        env:
          CI: true

      - name: Generate
        run: bun run generate
        env:
          CI: true
